# ldd (GNU libc) 2.17

FROM centos:centos7

WORKDIR src/

RUN curl -O https://raw.githubusercontent.com/rust-lang/rustup/master/rustup-init.sh \
  && yum -y install gcc \
  && sh rustup-init.sh -y \
  && source $HOME/.cargo/env \
  && rustup default nightly

ENV PATH="$HOME/.cargo/bin:$PATH"

CMD ["cargo", "build", "--release"]
