version: '3.2'
services:
  redis:
    image: coolbeevip/redis
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=mypassword
      - REDIS_MAXMEMORY=41943040
